In [6]:
import pandas as pd 
df= pd.read_excel('CustomerAnanlysis.xlsx')

In [10]:
df

,Customer_ID,Age,Tenure_Months,Monthly_Income,Visits_Per_Month,App_Usage_Hours,Satisfaction_Score,Support_Tickets,Discount_Usage_Pct,Payment_Delays,Membership_Tier,Acquisition_Channel,Customer_Lifetime_Value,Churn
0,C10001,40,81,91600.0,6.9,9.2,4.5,4.0,15.2,1.0,Basic,Paid Search,35598.0,0
1,C10002,35,63,89900.0,12.1,9.5,NaN,3.0,16.0,1.0,Silver,Referral,49009.0,0
2,C10003,42,38,110700.0,9.8,8.7,3.4,8.0,27.0,3.0,Silver,Social Media,22920.0,0
3,C10004,50,24,163600.0,13.5,8.1,7.1,5.0,0.0,1.0,Basic,Referral,53883.0,0
4,C10005,34,62,107600.0,5.8,3.8,5.1,4.0,14.0,0.0,Basic,Paid Search,32453.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C10996,33,34,125800.0,10.9,9.2,6.4,5.0,12.0,0.0,Platinum,Social Media,48338.0,0
996,C10997,52,24,137500.0,13.0,12.6,3.9,6.0,21.5,4.0,Silver,Referral,35914.0,1
997,C10998,42,99,149200.0,19.5,9.9,4.8,6.0,19.7,4.0,Gold,Social Media,51614.0,0
998,C10999,31,60,125500.0,NaN,6.9,5.6,4.0,16.0,0.0,Silver,Organic,54383.0,0
999,C11000,41,47,122800.0,7.2,NaN,6.1,5.0,23.9,1.0,Gold,Paid Search,38012.0,0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Customer_ID              1000 non-null   str
 1   Age                      1000 non-null   int64
 2   Tenure_Months            1000 non-null   int64
 3   Monthly_Income           967 non-null    float64
 4   Visits_Per_Month         975 non-null    float64
 5   App_Usage_Hours          970 non-null    float64
 6   Satisfaction_Score       960 non-null    float64
 7   Support_Tickets          976 non-null    float64
 8   Discount_Usage_Pct       970 non-null    float64
 9   Payment_Delays           980 non-null    float64
 10  Membership_Tier          975 non-null    str
 11  Acquisition_Channel      1000 non-null   str
 12  Customer_Lifetime_Value  980 non-null    float64
 13  Churn                    1000 non-null   int64
dtypes: float64(8), int64(3), str(3)
memory usage: 129.9 KB

In [8]:
df.describe()

,Age,Tenure_Months,Monthly_Income,Visits_Per_Month,App_Usage_Hours,Satisfaction_Score,Support_Tickets,Discount_Usage_Pct,Payment_Delays,Customer_Lifetime_Value,Churn
count,1000.000000,1000.000000,967.000000,975.000000,970.000000,960.000000,976.00000,970.000000,980.000000,980.000000,1000.000000
mean,36.285000,42.594000,110008.686660,9.844205,7.363093,6.357292,4.73668,16.188351,0.915306,46342.418367,0.111000
std,8.684423,24.083587,34952.810943,5.064474,3.130617,1.199326,2.44138,8.799201,1.012673,14650.769541,0.314289
min,17.000000,2.000000,20500.000000,1.000000,0.200000,2.600000,2.00000,0.000000,-2.000000,5779.000000,0.000000
25%,30.000000,24.000000,90600.000000,7.550000,5.200000,5.500000,4.00000,10.400000,0.000000,37186.500000,0.000000
50%,36.000000,38.000000,107600.000000,9.600000,7.350000,6.400000,4.00000,15.750000,1.000000,45744.000000,0.000000
75%,42.000000,55.000000,127350.000000,11.700000,9.400000,7.200000,6.00000,21.400000,1.000000,54655.500000,0.000000
max,72.000000,120.000000,500000.000000,85.000000,18.700000,10.000000,45.00000,95.000000,5.000000,240000.000000,1.000000

In [9]:
df.isnull

<bound method DataFrame.isnull of     Customer_ID  Age  Tenure_Months  Monthly_Income  Visits_Per_Month  \
0        C10001   40             81         91600.0               6.9
1        C10002   35             63         89900.0              12.1
2        C10003   42             38        110700.0               9.8
3        C10004   50             24        163600.0              13.5
4        C10005   34             62        107600.0               5.8
..          ...  ...            ...             ...               ...
995      C10996   33             34        125800.0              10.9
996      C10997   52             24        137500.0              13.0
997      C10998   42             99        149200.0              19.5
998      C10999   31             60        125500.0               NaN
999      C11000   41             47        122800.0               7.2

     App_Usage_Hours  Satisfaction_Score  Support_Tickets  Discount_Usage_Pct  \
0                9.2                 4.5              4.0                15.2
1                9.5                 NaN              3.0                16.0
2                8.7                 3.4              8.0                27.0
3                8.1                 7.1              5.0                 0.0
4                3.8                 5.1              4.0                14.0
..               ...                 ...              ...                 ...
995              9.2                 6.4              5.0                12.0
996             12.6                 3.9              6.0                21.5
997              9.9                 4.8              6.0                19.7
998              6.9                 5.6              4.0                16.0
999              NaN                 6.1              5.0                23.9

     Payment_Delays Membership_Tier Acquisition_Channel  \
0               1.0           Basic         Paid Search
1               1.0          Silver            Referral
2               3.0          Silver        Social Media
3               1.0           Basic            Referral
4               0.0           Basic         Paid Search
..              ...             ...                 ...
995             0.0        Platinum        Social Media
996             4.0          Silver            Referral
997             4.0            Gold        Social Media
998             0.0          Silver             Organic
999             1.0            Gold         Paid Search

     Customer_Lifetime_Value  Churn
0                    35598.0      0
1                    49009.0      0
2                    22920.0      0
3                    53883.0      0
4                    32453.0      0
..                       ...    ...
995                  48338.0      0
996                  35914.0      1
997                  51614.0      0
998                  54383.0      0
999                  38012.0      0

[1000 rows x 14 columns]>